# Q-Table Learning

In [1]:
import gym
import numpy as np

### Load the environment

In [2]:
env = gym.make('FrozenLake-v0')

### Implement Q-Table learning algorithm

In [3]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [4]:
print "Score over time: " +  str(sum(rList)/num_episodes)

Score over time: 0.5925


In [5]:
print "Final Q-Table Values"
print Q

Final Q-Table Values
[[4.33536127e-01 7.56265145e-03 8.99275997e-03 5.92873198e-03]
 [7.84456427e-05 2.80520014e-03 9.72020215e-04 1.62755075e-01]
 [2.26651893e-01 3.57895074e-03 6.01049830e-03 3.68464982e-03]
 [1.19205464e-03 7.34402814e-04 7.52224872e-04 6.31544587e-03]
 [6.11943046e-01 0.00000000e+00 8.04474828e-04 1.02641626e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.79550626e-04 5.19988665e-08 1.79189691e-01 5.31918569e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.77727084e-05 2.32405513e-03 1.17538975e-03 3.34865109e-01]
 [4.91879170e-03 6.02769260e-01 1.87029796e-03 0.00000000e+00]
 [6.76524977e-01 8.82326761e-04 4.98840633e-05 1.14049869e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.29268985e-03 0.00000000e+00 6.07200437e-01 1.70090770e-03]
 [0.00000000e+00 9.67122065e-01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.