In [1]:
input_width = 160
input_height = 100
class_number = 12
data_path = "D:\\Python\\Wormax_learn2\\preprocessed_data_local_notshuffled\\"

In [2]:
from keras.models import Sequential, Model
from keras import layers, models
import keras.backend as K
from keras.applications import Xception

conv_base = Xception(weights='imagenet',
                    include_top=False,
                    input_shape=(input_height, input_width, 3))

def actual_acc(y_true, y_pred):
    return K.equal(K.argmax(y_pred), K.argmax(y_true))


def define_model():
    model = models.Sequential(name='gamma')
    model.add(conv_base)
    model.add(layers.Flatten())
    model.add(layers.Dense(256, activation='relu'))
    model.add(layers.Dense(256, activation='relu'))
    
    model.add(layers.Dense(class_number, activation='softmax'))
   
    model.compile(optimizer='rmsprop', loss='categorical_crossentropy',
                  metrics=[actual_acc])
    
    model.summary()
    return model

Q:\Program Files\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [3]:
model = define_model()
model.load_weights('worm1_transfer_single_delme.h5')

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
xception (Model)             (None, 3, 5, 2048)        20861480  
_________________________________________________________________
flatten_1 (Flatten)          (None, 30720)             0         
_________________________________________________________________
dense_1 (Dense)              (None, 256)               7864576   
_________________________________________________________________
dense_2 (Dense)              (None, 256)               65792     
_________________________________________________________________
dense_3 (Dense)              (None, 12)                3084      
Total params: 28,794,932
Trainable params: 28,740,404
Non-trainable params: 54,528
_________________________________________________________________


In [4]:
import numpy as np
data = np.load(data_path + 'preprocessed-0-10000.npy')

In [9]:
cl = [0 for i in range(class_number)]
np.random.shuffle(data)
for unit in data[:100]:
    img = np.expand_dims(unit[0], axis=0)
    #img = np.zeros((1,input_height, input_width, 3))
    img = img/255
    #print(img[0][50][50])
    print(np.round(model.predict(img),2))
    cl[np.argmax(model.predict(img))] += 1
print(cl)

[[0.08 0.08 0.08 0.08 0.08 0.09 0.09 0.08 0.08 0.09 0.08 0.09]]
[[0.08 0.08 0.08 0.08 0.08 0.09 0.09 0.08 0.08 0.09 0.08 0.09]]
[[0.08 0.06 0.09 0.07 0.04 0.11 0.11 0.09 0.08 0.09 0.08 0.1 ]]
[[0.08 0.08 0.08 0.08 0.08 0.09 0.09 0.08 0.08 0.09 0.08 0.09]]
[[0.08 0.08 0.08 0.08 0.08 0.09 0.09 0.08 0.08 0.09 0.08 0.09]]
[[0.08 0.08 0.08 0.08 0.08 0.09 0.09 0.08 0.08 0.09 0.08 0.09]]
[[0.08 0.08 0.08 0.08 0.08 0.09 0.09 0.08 0.08 0.09 0.08 0.09]]
[[0.08 0.08 0.08 0.08 0.08 0.09 0.09 0.08 0.08 0.09 0.08 0.09]]
[[0.08 0.08 0.09 0.08 0.05 0.1  0.1  0.08 0.08 0.09 0.08 0.09]]
[[0.08 0.08 0.08 0.08 0.08 0.09 0.09 0.08 0.08 0.09 0.08 0.09]]
[[0.08 0.08 0.08 0.08 0.08 0.09 0.09 0.08 0.08 0.09 0.08 0.09]]
[[0.08 0.07 0.09 0.07 0.04 0.11 0.1  0.09 0.08 0.09 0.08 0.1 ]]
[[0.08 0.08 0.08 0.08 0.08 0.09 0.09 0.08 0.08 0.09 0.08 0.09]]
[[0.08 0.08 0.08 0.08 0.08 0.09 0.09 0.08 0.08 0.09 0.08 0.09]]
[[0.08 0.08 0.08 0.08 0.08 0.09 0.09 0.08 0.08 0.09 0.08 0.09]]
[[0.08 0.08 0.08 0.08 0.06 0.1  0.09 0.0

In [20]:
layers = model.layers
layers[-1].get_weights()

[array([[-0.23699804, -0.31183216, -0.274653  , ..., -0.31733847,
         -0.2737811 , -0.33603382],
        [-0.6613067 , -0.8364251 , -0.99792963, ..., -0.697529  ,
         -0.6338342 , -0.66410816],
        [-1.2055858 , -1.1149814 , -1.2724276 , ..., -1.4351267 ,
         -1.4256327 , -1.1394081 ],
        ...,
        [-1.4129453 , -1.6519395 , -1.5061723 , ..., -1.7694294 ,
         -1.729774  , -1.4196603 ],
        [-0.9045044 , -0.6492117 , -0.8720988 , ..., -0.72558624,
         -0.9055583 , -0.8738495 ],
        [-0.9380581 , -1.0378897 , -1.2558414 , ..., -0.84243053,
         -1.0225418 , -0.972011  ]], dtype=float32),
 array([-0.02083502, -0.3179785 , -0.4920583 , -0.6407207 , -0.52229017,
        -0.26279312,  0.04341902, -0.19297054, -0.3953036 , -0.48467368,
        -0.3775534 , -0.14411733], dtype=float32)]

In [38]:
count = [142651.,  88202.,  53316.,  42411.,  56847.,  93134.,  142271.,  104377.,  66154.,  54558.,  70020., 110059.]
count = np.array(count)
count = count/max(count)
count = np.round(1/count,2)
class_weights = {}
for i in range(len(count)):
    class_weights[i] = count[i]
class_weights

{0: 1.0,
 1: 1.62,
 2: 2.68,
 3: 3.36,
 4: 2.51,
 5: 1.53,
 6: 1.0,
 7: 1.37,
 8: 2.16,
 9: 2.61,
 10: 2.04,
 11: 1.3}

In [5]:
from keras.models import load_model
import keras.backend as K
def actual_acc(y_true, y_pred):
    return K.equal(K.argmax(y_pred), K.argmax(y_true))

model = load_model('worm_single_large_adam.h5',custom_objects={'actual_acc':actual_acc})

In [6]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 98, 158, 32)       896       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 49, 79, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 47, 77, 64)        18496     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 23, 38, 64)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 21, 36, 128)       73856     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 10, 18, 128)       0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 8, 16, 128)        147584    
__________

In [5]:
import keras
mdl = keras.applications.vgg16.VGG16(include_top=False, weights='imagenet', input_tensor=None, input_shape=None, pooling=None, classes=1000)
mdl.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         (None, None, None, 3)     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, None, None, 64)    1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, None, None, 64)    36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, None, None, 64)    0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, None, None, 128)   73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, None, None, 128)   147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, None, None, 128)   0         
__________